version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: taskmanager
      POSTGRES_USER: neondb_owner
      POSTGRES_PASSWORD: npg_Q0VkCbHw6WBN
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: rest-taskmanager
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_HOST: db
      DB_NAME: taskmanager
      DB_USERNAME: neondb_owner
      DB_PASSWORD: npg_Q0VkCbHw6WBN
    depends_on:
      - db

volumes:
  pgdata: